work around bugs in curl on cygwin

diff --git a/install b/install
--- a/install
+++ b/install
@@ -375,24 +375,27 @@ if [ -n "$url" ]; then
     echo "${_Y}===>${_0} fetching ${_U}${url##*/}${_0}"
   fi
 
-  set +e
+  (
+    cd -- "${file%/*}"
+    file="${file##*/}"
 
-  if command -v curl >/dev/null 2>&1; then
-    err="$(command curl -fsSLo "$file" -- "$url" 2>&1)"
-  elif command -v wget >/dev/null 2>&1; then
-    err="$(command wget -O "$file" -- "$url" 2>&1)"
-  else
-    >&2 echo "${_R}error${_0}: please install ${_G}curl${_0} or ${_G}wget${_0} and retry"
-    exit 1
-  fi
+    set +e
 
-  if [ $? != 0 ]; then
-    >&2 printf "%s\n" "$err"
-    >&2 echo "${_R}error${_0}: failed to download ${_U}$url${_0}"
-    exit 1
-  fi
+    if command -v curl >/dev/null 2>&1; then
+      err="$(command curl -fsSLo "$file" -- "$url" 2>&1)"
+    elif command -v wget >/dev/null 2>&1; then
+      err="$(command wget -O "$file" -- "$url" 2>&1)"
+    else
+      >&2 echo "${_R}error${_0}: please install ${_G}curl${_0} or ${_G}wget${_0} and retry"
+      exit 1
+    fi
 
-  set -e
+    if [ $? != 0 ]; then
+      >&2 printf "%s\n" "$err"
+      >&2 echo "${_R}error${_0}: failed to download ${_U}$url${_0}"
+      exit 1
+    fi
+  )
 else
   cleanup() { true; }
 fi
